# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: test-screwdriver
env: prod
# Set it to true if your apps are running with https protocol
https: false

# Please enable it for RBAC enabled k8s cluster
rbac:
  enabled: false

nginx:
  # If your k8s cluster does not use nginx as Load Balancer, set it to false
  enabled: true
  # If you want screwdriver chart to create a nginx server for you, set it to true
  create: false
  image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.18.0
  backend_image: gcr.io/google_containers/defaultbackend:1.0

ingress:
  # Use tls or not, if set to true, please refer to ingress.yaml and create tls secrets accordingly
  # Reference: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  tls: false
  annotations:
    # Override these annotations based on your load balancer configurations
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
  # This property allows for reports up to a certain size to be uploaded to SonarQube
  # nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    api: test-api.screwdriver.cd
    ui: test-cd.screwdriver.cd
    store: test-store.screwdriver.cd
  # Enabled singleHost if your api, store, ui are sharing the same host with different path
  singleHost:
    enabled: false
    # Same host with different path example
    # apiPath: /api
    # uiPath: /ui
    # storePath: /store
    apiPath: ""
    uiPath: ""
    storePath: ""

# Set up build notifications or not, if yes please add notification config in your screwdirver-api-secret file
# Reference config: https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L235
notifications:
  enabled: false

api:
  image: screwdrivercd/screwdriver:v0.5.486
  replicas: 1

ui:
  image: screwdrivercd/ui:v1.0.344
  avatarHost: "*.githubusercontent.com"
  replicas: 1

store:
  image: screwdrivercd/store:v3.3.5
  replicas: 1
  # if s3 is not enabled, will use pod's memory to store logs, artifacts and that't non-persistent
  s3:
    enabled: false
    bucketName: your.s3.bucket.name
    region: us-east-2
    useAccessKey: false

launcher:
  image: screwdrivercd/launcher
  version: v5.0.30

# Enable queue feature or not, this will bring up a queue-worker pod and a redis pod
queue:
  enabled: false
  image: screwdrivercd/queue-worker:v2.2.3

# Queue for screwdriver
# Please refer to https://github.com/helm/charts/tree/master/stable/redis for more configurations
redis:
  cluster:
    enabled: false
  master:
    persistence:
      # To specify non-default storageClass, uncomment the line below and set it accordingly
      # storageClass: "enc-gp2"
      # Enabled it if you want you data to be persistent
      enabled: false
      size: 10Gi

# Database for screwdriver api, can be either running as a pod or external
# Please refer to https://github.com/helm/charts/tree/master/stable/postgresql for more configurations
postgresql:
  enabled: true
  # To use an external PostgreSQL instance, follow the steps:
  # 1. add a record to your screwdirver-api-secret file with key postgres-password with real password
  # 2. set postgressql enabled to false to prevent creation of postgres as a pod
  # 3. uncomment the line below with your externl postgres server
  # postgresServer: ""
  postgresUser: "sdUser"
  postgresPassword: "sdPassword"
  postgresDatabase: "screwdriver"
  # Specify the TCP port that PostgreSQL should use
  service:
    port: 5432
  persistence:
    # To specify non-default storageClass, uncomment the line below and set it accordingly
    # storageClass: "enc-gp2"
    # Enabled it if you want you data to be persistent
    enabled: false
    size: 20Gi
